### ISSUE TITLE
uninitialized memory being printed after end of HTTP response

### ISSUE THREAD

**Issue by kevinburke** [hyperium/hyper#2512]
I'm using curl commit `52fab72` compiled with Hyper 0.14.6 and the latest crustls commit. On Mac you can compile curl with the Hyper backend by using the following Homebrew formula:

```
brew install meterup/safe/curl
```

You can inspect the formula for yourself here: https://github.com/meterup/homebrew-safe.

Maybe 1 in every 20 HTTP requests I make, curl prints what appears to be uninitialized memory after the end of the HTTP response. It looks like this:

```
/usr/local/opt/curl/bin/curl \
    --silent \
    --show-error \
    --max-time "180" \
    --include \
    --request "GET" \
    --header "User-Agent: mcurl/1.176" \
    --header "Date: Thu, 22 Apr 2021 20:20:22 GMT" \
    --header "Keyname: api" \
    --header "Authorization:Meter secret" \
    https://meterapi.dev/v1/controllers/2011ba0629
HTTP/2 200 OK
date: Thu, 22 Apr 2021 20:20:46 GMT
content-type: application/json; charset=utf-8
content-length: 164
host-sid: 4a7cfb60-d6cd-4ecd-ba8f-9005b7d870f9
server: meter-api/1.178
strict-transport-security: max-age=31536000; preload
x-request-duration: 3.2ms

{
 "sid": "a1020efc-a6cc-4e3c-a5ea-36bd515a1d69",
 "created_at": "2020-11-24T20:55:56.792358Z",
 "updated_at": "2021-02-11T18:06:32.045429Z",
 "status": "online"
}
C61-4094-5BE81E368179.icc�1236_DeviceDescriptions_FactoryProfiles�45Uen_US_v15: if lost call 9252717005�7897Y555810816_DeviceDefaultProfileID�:;<>_DeviceModeDescriptions_DeviceProfileURL�4=WDefault_[/System/Library/Frameworks/ICADevices.framework/Versions/A/Resources/Camera RGB Profile.icc�@A^CustomProfiles�.B_F/Users/kevin/Library/ColorSync/Profiles/f.lux/fluxprofile-2531a33c.icc�DE^CustomProfiles�.F_F/Users/kevin/Library/ColorSync/Profiles/f.lux/fluxprofile-d43b9ac5.icc�HI^CustomProfiles�.J_S/Library/ColorSync/Profiles/Displays/LG TV-86777883-A061-5674-DC7D-9B1D37C869AB.icc�12LN�4M_CanoScan LiDE 220�OP8QUPY286326784Y287375360�:;RT�4S_Reflective Gray_E/System/Library/ColorSync/Profiles/Generic Gray Gamma 2.2 Profile.icc�:;VX�4W^Re
```

I have omitted some fields from the HTTP response since they contain private information and updated the Content-Length to match the new length of the HTTP response - 164 characters gets you to the `}` closing the JSON response. The original HTTP response contained extra JSON fields and was 528 characters, so the original `Content-Length` header read `528`, if that matters. The server is written in Go and deployed to a Linux host; the extra memory bits reference stuff on my Mac so the extra memory is not being streamed from the server somehow.

I am not sure whether the issue exists in curl or in Hyper, but Jacob Hoffman-Andrews suggested it would be good to start here. I cannot reproduce this issue using other Curl TLS backends, for example openssl.

**Comment by kevinburke** [comment]
Update, found a much simpler reproduction, just run this 20 times and you should see it 

```
 curl --output - https://public.meter.dev/misc/largefile.html
```

**Comment by jsha** [comment]
I've tried to reproduce this using curl 7.76.1, crustls 0.4.0, hyper v0.14.7, and rustc 1.52.0-nightly on Linux, but it doesn't repro for me, even running in a loop for 100 tries. It's possible there's something specific about building / running on macOS, or something specific about the Homebrew formula.

Can you update the Homebrew formula to pin specific versions of curl, crustls, and hyper, and confirm that it still reproduces (I'm guessing it will)? If so I'll see if I can get a macOS VM set up to test on.

**Comment by kevinburke** [comment]
Alright, well, interesting, I fixed the versions of everything and I can't reproduce it now. Let me see if I can reproduce with curl at tip.

**Comment by kevinburke** [comment]
I can reproduce with curl at tip but not at 7.76.1.

**Comment by kevinburke** [comment]
I can't reproduce with curl at tip and with the openssl backend. So it does seem specific to Hyper/crustls and tip.

**Comment by jsha** [comment]
For me, on Linux with:

- curl tip (67d3afa73f4cdb8a6c473f911c8af800121e0a49)
- crustls 0.4.0
- hyper v0.14.7

Still doesn't repro.

Would you mind doing some bisection between 7.76.1 to try and find where things changed? Happy to advise if you haven't used `git bisect` before.

You might also want to try just before and just after 40d2d39f86812d295008648f249a98d07f4c93ee (https://github.com/curl/curl/pull/6894), which touched rustls.

**Comment by kevinburke** [comment]
Gah, I'm very sorry. I can also reproduce on 7.76.1. When I said I couldn't reproduce at 7.76.1 I still had the rust instructions inside a `head?` if statement https://github.com/meterup/homebrew-safe/blob/main/Formula/curl.rb#L56-L60

When I modified that to do the right thing I can reproduce on 7.76.1 so I will have to look back further to see whether it was introduced by a commit or has been present since the rust changes were merged.

**Comment by kevinburke** [comment]
Bisected to curl/curl@f573998c22a20b0fbe4edb8dbd968aa2f7ca5864. With `-vvv` enabled

```
*   Trying 100.20.30.70:443...
* Connected to public.meter.dev (100.20.30.70) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: public.meter.dev
* Server certificate: Amazon
* Server certificate: Amazon Root CA 1
* Time for the Hyper dance
> GET /misc/largefile.html HTTP/2
> Host: public.meter.dev
> User-Agent: curl/7.76.0-DEV
> Accept: */*
>
< HTTP/2 200 OK
< date: Fri, 23 Apr 2021 00:18:47 GMT
< content-type: text/html; charset=utf-8
< content-length: 1384
< server: nginx
< last-modified: Thu, 22 Apr 2021 20:36:14 GMT
< etag: "6081de3e-568"
< accept-ranges: bytes
<
<!doctype html>
<html>
  <head>
    <title>Meter Public</title>
  </head>
  <body>
    <!-- attempt to trigger https://github.com/hyperium/hyper/issues/2512 -->
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  </body>
</html>
��M>߬�硈k1���3��Ej4��$(
�:[���S�M�7�%�"؎��^:�2�>��e�t�/�|�'4�)}���	���
�eet
* hyperstream is done!
* Connection #0 to host public.meter.dev left intact
�:Ye9Xz��r=��^�!���,��pROx��<+�����h� ~L\_���5�7�f��J΃W
```

**Comment by jsha** [comment]
Interesting. What happens before https://github.com/curl/curl/commit/f573998c22a20b0fbe4edb8dbd968aa2f7ca5864 ? Do you still get an HTTP/2 response?

**Comment by kevinburke** [comment]
No, HTTP 1.1

```
Trying 54.212.75.197:443...
* Connected to public.meter.dev (54.212.75.197) port 443 (#0)
* ALPN, offering http/1.1
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: public.meter.dev
* Server certificate: Amazon
* Server certificate: Amazon Root CA 1
* Time for the Hyper dance
> GET /misc/largefile.html HTTP/1.1
> Host: public.meter.dev
> User-Agent: curl/7.76.0-DEV
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 23 Apr 2021 02:21:46 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 1384
< Connection: keep-alive
< Server: nginx
< Last-Modified: Thu, 22 Apr 2021 20:36:14 GMT
< ETag: "6081de3e-568"
< Accept-Ranges: bytes
<
<!doctype html>
<html>
  <head>
    <title>Meter Public</title>
  </head>
  <body>
    <!-- attempt to trigger https://github.com/hyperium/hyper/issues/2512 -->
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  </body>
</html>
* hyperstream is done!
* Connection #0 to host public.meter.dev left intact
*
```

**Comment by jsha** [comment]
So it seems like there's a problem specific to HTTP/2. Also, I notice your -vvv output doesn't look like what I'd expect with rustls selected as the TLS engine. Can you do `curl --version`?

**Comment by kevinburke** [comment]
```
$ curl --version
curl 7.77.0-DEV (powerpc64-apple-darwin19.6.0) libcurl/7.77.0-DEV SecureTransport (crustls/0.3.0/rustls/0.19.0) zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.3.0 nghttp2/1.43.0 librtmp/2.3 Hyper/0.14.7
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 IDN IPv6 Largefile libz MultiSSL NTLM NTLM_WB SSL UnixSockets zstd
```

The reason it says 0.3.0 is the crustls `v0.4.0` git tag still has 0.3.0 in the Cargo.toml. This is how I'm configuring it. 

```
./configure --with-hyper=/usr/local/opt/hyper --with-rustls=/usr/local/opt/crustls --with-secure-transport && make && make install && rehash && /usr/local/bin/curl --version
```

**Comment by jsha** [comment]
Looks like your curl has both crustls and secure transport, and is choosing
the latter. There's no runtime flag to choose one or the other. I'd be
curious to see what a crustls-only build does.

The 0.3.0/0.4.0 is a packaging mistake on my part.

**Comment by kevinburke** [comment]
I tried 

```
./configure --with-hyper=/usr/local/opt/hyper --with-rustls=/usr/local/opt/crustls && make && make install && rehash && /usr/local/bin/curl --version
```

but now crustls doesn't show up in the version string at all

```
curl 7.77.0-DEV (powerpc64-apple-darwin19.6.0) libcurl/7.77.0-DEV zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.3.0 nghttp2/1.43.0 librtmp/2.3 Hyper/0.14.7
Release-Date: [unreleased]
Protocols: dict file ftp gopher http imap ldap ldaps mqtt pop3 rtmp smtp telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 IDN IPv6 Largefile libz UnixSockets zstd
```

which is probably why I added the securetransport flag to begin with. Going back to look at your wiki instructions

**Comment by kevinburke** [comment]
The crustls wiki suggests

```
./configure --with-hyper=/usr/local/opt/hyper --with-rustls=/usr/local/opt/crustls --without-ssl --enable-debug
``` 

Which doesn't have crustls in the version string either - it returns the same as above, and can't use HTTPS it doesn't look like.

**Comment by kevinburke** [comment]
Well, now I tried running `autoreconf -fi` for the first time in forever and I am getting this `configure: error: --with-rustls was specified but could not find rustls`, which I'm trying to work through.

**Comment by kevinburke** [comment]
I think it's impossible to configure curl with the `--with-rustls` flag on and without the `--with-secure-transport` flag. I get the same error in my Homebrew formula, which I know is setting the environment flags appropriately.

**Comment by kevinburke** [comment]
OK, so, narrowing down slightly - this is reproducible when you configure + compile curl with Hyper and SecureTransport, but _not_ with Hyper and Rustls. @jsha suspects that this is specifically a problem with HTTP/2 - the public.meter.dev server is an AWS ALB that returns HTTP/2 responses, and that a HTTP/1.1 server will not have the same uninitialized memory issues.

**Comment by kevinburke** [comment]
Compiling curl with AddressSanitizer turned on and it will repeatedly print the exact same number of garbage bytes at the end of each HTTP request.

```
<!doctype html>
<html>
  <head>
    <title>Meter Public</title>
  </head>
  <body>
    <!-- attempt to trigger https://github.com/hyperium/hyper/issues/2512 -->
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  </body>
</html>
����������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
```

**Comment by jsha** [comment]
I've reproduced this on both macOS and Linux. This only reproduces for HTTP/2 requests. To get it to reproduce, you need to build curl with both nghttp2 and Hyper, because the code that decides which ALPN protocols to offer (http/1.1 vs http/1.1 _and_ h2) is gated on USE_NGHTTP2 (though it should probably be gated on something else since Hyper also offers HTTP/2 support).

Here's the curl ./configure command I used to build on Linux:

```
CC=clang CFLAGS="-fsanitize=address,undefined,signed-integer-overflow -fno-sanitize-recover=undefined,integer -Wformat -Werror=format-security -Werror=array-bounds -g" CXXFLAGS="-fsanitize=address,undefined -fno-sanitize-recover=undefined,integer -Wformat -Werror=format-security -Werror=array-bounds -g" LDFLAGS="-fsanitize=address,undefined -fno-sanitize-recover=undefined,integer" LIBS="-ldl" ./configure --with-hyper=${HOME}/rust/hyper --with-openssl --disable-shared --enable-werror --enable-debug
```

<details><summary>curl output piped to xxd</summary>

```
$ ./src/curl ./src/curl -vvv https://public.meter.dev/misc/largefile.html 2>err.log | xxd
00000000: 3c21 646f 6374 7970 6520 6874 6d6c 3e0a  <!doctype html>.
00000010: 3c68 746d 6c3e 0a20 203c 6865 6164 3e0a  <html>.  <head>.
00000020: 2020 2020 3c74 6974 6c65 3e4d 6574 6572      <title>Meter
00000030: 2050 7562 6c69 633c 2f74 6974 6c65 3e0a   Public</title>.
00000040: 2020 3c2f 6865 6164 3e0a 2020 3c62 6f64    </head>.  <bod
00000050: 793e 0a20 2020 203c 212d 2d20 6174 7465  y>.    <!-- atte
00000060: 6d70 7420 746f 2074 7269 6767 6572 2068  mpt to trigger h
00000070: 7474 7073 3a2f 2f67 6974 6875 622e 636f  ttps://github.co
00000080: 6d2f 6879 7065 7269 756d 2f68 7970 6572  m/hyperium/hyper
00000090: 2f69 7373 7565 732f 3235 3132 202d 2d3e  /issues/2512 -->
000000a0: 0a20 2020 2061 6161 6161 6161 6161 6161  .    aaaaaaaaaaa
000000b0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000000c0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000000d0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000000e0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000000f0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000100: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000110: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000120: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000130: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000140: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000150: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000160: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000170: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000180: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000190: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000001a0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000001b0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000001c0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000001d0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000001e0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000001f0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000200: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000210: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000220: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000230: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000240: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000250: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000260: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000270: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000280: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000290: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000002a0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000002b0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000002c0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000002d0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000002e0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000002f0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000300: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000310: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000320: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000330: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000340: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000350: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000360: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000370: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000380: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000390: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000003a0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000003b0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000003c0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000003d0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000003e0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000003f0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000400: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000410: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000420: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000430: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000440: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000450: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000460: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000470: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000480: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000490: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000004a0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000004b0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000004c0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000004d0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000004e0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
000004f0: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000500: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000510: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000520: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000530: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000540: 6161 6161 6161 6161 6161 6161 6161 6161  aaaaaaaaaaaaaaaa
00000550: 6161 6161 610a 2020 3c2f 626f 6479 3e0a  aaaaa.  </body>.
00000560: 3c2f 6874 6d6c 3e0a bebe bebe bebe bebe  </html>.........
00000570: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000580: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000590: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000005a0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000005b0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000005c0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000005d0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000005e0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000005f0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000600: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000610: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000620: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000630: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000640: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000650: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000660: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000670: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000680: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000690: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000006a0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000006b0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000006c0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000006d0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000006e0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000006f0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000700: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000710: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000720: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000730: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000740: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000750: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000760: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000770: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000780: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000790: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000007a0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000007b0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000007c0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000007d0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000007e0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000007f0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000800: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000810: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000820: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000830: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000840: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000850: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000860: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000870: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000880: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000890: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000008a0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000008b0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000008c0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000008d0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000008e0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000008f0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000900: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000910: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000920: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000930: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000940: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000950: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000960: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000970: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000980: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000990: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000009a0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000009b0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000009c0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000009d0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000009e0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
000009f0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000a00: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000a10: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000a20: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000a30: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000a40: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000a50: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000a60: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000a70: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000a80: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000a90: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000aa0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000ab0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000ac0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000ad0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000ae0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000af0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000b00: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000b10: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000b20: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000b30: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000b40: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000b50: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000b60: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000b70: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000b80: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000b90: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000ba0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000bb0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000bc0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000bd0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000be0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000bf0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000c00: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000c10: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000c20: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000c30: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000c40: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000c50: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000c60: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000c70: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000c80: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000c90: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000ca0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000cb0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000cc0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000cd0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000ce0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000cf0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000d00: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000d10: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000d20: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000d30: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000d40: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000d50: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000d60: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000d70: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000d80: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000d90: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000da0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000db0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000dc0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000dd0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000de0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000df0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000e00: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000e10: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000e20: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000e30: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000e40: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000e50: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000e60: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000e70: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000e80: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000e90: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000ea0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000eb0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000ec0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000ed0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000ee0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000ef0: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000f00: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000f10: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000f20: bebe bebe bebe bebe bebe bebe bebe bebe  ................
00000f30: bebe                                     ..
```

**Comment by jsha** [comment]
When we build with AddressSanitizer the extra bytes we see are 0xbe. Per https://github.com/google/sanitizers/wiki/AddressSanitizerFlags#run-time-flags:

> malloc_fill_byte | 0xbe | Value used to fill the newly allocated memory.

So we're reading data that is properly allocated, but has not been initialized.

**Comment by kevinburke** [comment]
Patch has been merged to curl/curl, closing!

**Comment by seanmonstar** [comment]
Oh fantastic! Thanks so much for how you dug into it. When I read the conclusion that it seemed like it was coming from HTTP2, I started poking around in hyper's h2 code, muttering to myself "but where could this possibly be happening?". XD

**Comment by sfackler** [comment]
Seems a bit weird that hyper's returning 0 length body chunks though.
